name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm i 
    - run: node --test

  build:
    needs: test
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ttl.sh/mega-api:3h  # Add the 'run' key here
    - run: docker push ttl.sh/mega-api:3h

  deploy_staging:
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy staging
      env:
        STAGING_KEY: ${{ secrets.STAGING_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${STAGING_KEY}"
    - run: ssh -i ~/.ssh/id_rsa vagrant@192.168.105.3 'sudo docker stop running-api || true'
    - run: ssh -i ~/.ssh/id_rsa vagrant@192.168.105.3 'sudo docker rm running-api || true'
    - run: ssh -i ~/.ssh/id_rsa vagrant@192.168.105.3 'sudo docker run --pull always -d --restart=unless-stopped --name running-api -p 4444:4444 ttl.sh/amazing-api:1h'
