name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm i 
    - run: node --test

  build:
    needs: test
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ttl.sh/mega-api:3h
    - name: Test Docker image
      run: docker run --rm --name test-container ttl.sh/mega-api:3h & sleep 10; docker ps | grep test-container
    - run: docker push ttl.sh/mega-api:3h

  deploy_staging:
    needs: build
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy staging
      env:
        STAGING_KEY: ${{ secrets.STAGING_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${STAGING_KEY}"
        ssh vagrant@192.168.105.3 'docker-compose down || true'
        ssh vagrant@192.168.105.3 'docker-compose up -d'

  deploy_prod:
    needs: deploy_staging
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Prod
      env:
        AWS_KEY: ${{ secrets.AWS_KEY }}
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${AWS_KEY}"
        ssh ubuntu@ec2-52-59-114-177.eu-central-1.compute.amazonaws.com 'docker-compose down || true'
        ssh ubuntu@ec2-52-59-114-177.eu-central-1.compute.amazonaws.com 'docker-compose up -d'
